---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # HelmRepository definitions
  - helm/cilium.yaml
  - helm/cnpg.yaml
  - helm/codecentric.yaml
  - helm/dragonfly.yaml
  - helm/external-secrets.yaml
  - helm/jetstack.yaml
  - helm/openebs.yaml
  - helm/prometheus-community.yaml
  - helm/rook-ceph.yaml
  - helm/stakater.yaml
  - helm/strimzi.yaml
  # OCIRepository definitions
  - oci/app-template.yaml
  - oci/cloudflared.yaml
  - oci/envoy-gateway.yaml
  - oci/external-dns.yaml
  - oci/ghcr-flux.yaml
  - oci/ghcr-sidero.yaml
  - oci/grafana.yaml
  - oci/victoria-logs.yaml
  - oci/victoria-metrics.yaml
